---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dash0-credentials
  namespace: dash0
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: dash0-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: clusters/${cluster_name}/dash0
