apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: image-pull-secrets
spec:
  externalSecretName: image-pull-secrets
  refreshTime: 1h
  namespaceSelectors:
  - matchLabels:
      imagepullsecrets-externalsecret: enabled
  externalSecretSpec:                        # this is the spec of the ExternalSecrets created
    secretStoreRef:
      name: secret-store
      kind: ClusterSecretStore
    target:
      name: image-pull-secrets
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {"auths":{"https://index.docker.io/v1/":{"auth":"{{ printf "%s:%s" .docker_user .docker_token | b64enc }}"}}}
    dataFrom:
    - extract:
        key: clusters/${cluster_name}/image-pull-secrets
--- 
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enable-imagepullsecrets-externalsecret-across-namespaces
  annotations:
    policies.kyverno.io/title: Make imagepullsecret available in all namespaces
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/minversion: 1.6.0
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: enable-imagepullsecrets-externalsecret-across-namespaces
      match:
        any:
          - resources:
              kinds:
                - Namespace
      mutate:
        targets: 
          - apiVersion: v1 
            kind: Namespace
        patchStrategicMerge:
          metadata:
            labels:
              imagepullsecrets-externalsecret: enabled
