---
apiVersion: app-conveyor.elifesciences.org/v1alpha1
kind: Pipeline
metadata:
  name: epp--staging-epp-client
  namespace: epp--staging
spec:
  name: Enhanced Preprints Client (staging)
  pollIntervalMs: 60000
  steps:
    - id: src
      type: git
      repo: elifesciences/enhanced-preprints-client
      branch: master

    - id: ci
      type: gha
      repo: elifesciences/enhanced-preprints-client
      workflow: ci.yaml

    - id: reg
      type: ghcr
      image: ghcr.io/elifesciences/enhanced-preprints-client

    - id: auto
      type: flux-image
      policy: epp-client
      automation: epp-automation
      namespace: epp--staging

    - id: sync
      type: flux-kustomize
      name: epp--staging
      automation: epp-automation
      namespace: epp--staging

    - id: live
      type: k8s-deploy
      name: epp-client
      namespace: epp--staging
