pipelines:
  - id: app-conveyor
    name: App Conveyor
    pollIntervalMs: 60000
    steps:
      - id: src
        type: git
        repo: elifesciences/app-conveyor
        branch: main

      - id: ci
        type: gha
        repo: elifesciences/app-conveyor
        workflow: build-push.yml

      - id: reg
        type: ghcr
        image: ghcr.io/elifesciences/app-conveyor

      - id: auto
        type: flux-image
        policy: app-conveyor
        automation: app-conveyor
        namespace: app-conveyor

      - id: sync
        type: flux-kustomize
        name: app-conveyor
        automation: app-conveyor
        namespace: app-conveyor

      - id: live
        type: k8s-deploy
        kind: StatefulSet
        name: app-conveyor
        namespace: app-conveyor
