apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-conveyor
resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - image-automation.yaml
configMapGenerator:
  - name: app-conveyor-config
    files:
      - conveyor.yaml
