---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-conveyor-github
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: app-conveyor-github
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: clusters/flux-prod/app-conveyor
